http:
  routers:
    dolciaria-farina:
      rule: "Host(`farina.fodivps1.cloud`)"
      entryPoints:
        - websecure
      service: dolciaria-farina
      tls:
        certResolver: letsencrypt

  services:
    dolciaria-farina:
      loadBalancer:
        servers:
          - url: "http://172.19.0.1:3035"
