http:
  routers:
    saas-generali:
      rule: Host(`saas-generali.fodivps1.cloud`)
      service: saas-generali
      entrypoints:
        - websecure
      tls:
        certResolver: letsencrypt
      middlewares:
        - saas-generali-headers
        - compress@file

  services:
    saas-generali:
      loadBalancer:
        servers:
          - url: "http://172.19.0.1:3010"

  middlewares:
    saas-generali-headers:
      headers:
        sslRedirect: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        customFrameOptionsValue: "SAMEORIGIN"
