http:
  routers:
    unsic:
      rule: "Host(`unsic.fodivps1.cloud`)"
      service: unsic
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      middlewares:
        - security-headers@file
        - compress@file

  services:
    unsic:
      loadBalancer:
        servers:
          - url: "http://172.19.0.1:3025"
